### ISSUE TITLE
Any plans on Quark Compat?

### ISSUE THREAD

**Issue by Afrocntrik** [jsburger/Architects-Palette#1]
But holy shit I love this mod!
![2021-01-09_01 37 34](https://user-images.githubusercontent.com/11052983/104085218-a6257780-521b-11eb-8601-5f3004f7c529.png)
Just trying out the colors!

Also is the withered osseous block greenish relative to the bone block form?
![2021-01-09_01 39 58](https://user-images.githubusercontent.com/11052983/104085248-eb49a980-521b-11eb-925a-9a461a9e20cc.png)

**Comment by jsburger** [comment]
Glad to see people are enjoying exploring the options! There are in fact plans for Quark compatibility, they just haven't been taken care of yet. I wanted to get the first release out before spending time investing in outside compatibility. You'll even find that there are textures for Quark's additional wood blocks included in the files, just unused. I also believe that the Osseous Bricks are deliberately lighter to make them more palatable as bricks. The green might be coming from the fact that you are in the end.

**Comment by pm065** [comment]
Adding on to this: Could there be a Soul Sandstone version of the Sandstone blocks? Maybe they could have embedded quartz instead of gold? Or use netherite scraps? Small bits of netherite scraps (with crafting recipes like nuggets) to make large quantities viable?

Atmospheric Arid Sandstone compatibility would be pretty nice too, using iron or something...
